server:
  port: 8081


spring:
  jackson:
    serialization:
      indent_output: true

  datasource:
    url: jdbc:h2:~/fiapcervejaria;DB_CLOSE_ON_EXIT=false
    username: fiap
    password: password